spring:
  jpa:
    properties:
      hibernate.globally_quoted_identifiers: true

  mvc:
    format:
      date: iso
      date-time: iso
      time: iso

  jackson:
    visibility.field: any
    visibility.getter: none
    visibility.setter: none
    visibility.is-getter: none

  messages:
    fallback-to-system-locale: false

server:
  forward-headers-strategy: framework
