spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.globally_quoted_identifiers: true
  datasource:
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE

  mvc:
    format:
      date: iso
      date-time: iso
      time: iso

  jackson:
    visibility.field: any
    visibility.getter: none
    visibility.setter: none
    visibility.is-getter: none
